language: node_js
node_js:
  - "iojs"
  - "node"
addons:
  sonarcloud:
    organization: "kmindi-github" # the key of the org you chose at step #3
cache:
 directories:
   - "node_modules"
before_script:
   - grunt build
script:

  - npm test
  - sonar-scanner
